- id: gha-guard
  name: gha-guard
  description: Scan GitHub Actions workflow files for security vulnerabilities.
  language: python
  entry: gha-guard scan
  files: ^\.github/workflows/.*\.(yml|yaml)$
  pass_filenames: false
  additional_dependencies: []
